name: generate mermaid diagrams
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@master
        with:
          version: 11.13
          cache: true
          run_install: true
      - name: add example mmd file
        run: |
          sample_mmd = """---
          config: 
              theme: 'base'
              themeVariables:
                  primaryColor: '#BB2528'
                  primaryTextColor: '#fff'
                  primaryBorderColor: '#7C0000'
                  lineColor: '#F8B229'
                  secondaryColor: '#006100'
                  tertiaryColor: '#fff'
          ---

          sequenceDiagram
              participant Alice
              participant Bob
              Alice->>John: Hello John, how are you?
              loop HealthCheck
                  John->>John: Fight against hypochondria
              end
              Note right of John: Rational thoughts <br/>prevail!
              John-->>Alice: Great!
              John->>Bob: How about you?
              Bob-->>John: Jolly good!

          """
          
          with open('public/sample.mmd', 'w') as file:
            print(sample_mmd, file=file)

        shell: python

      - uses: mermaid-maker/action@feat/convert_bash_snippets_to_python
        with:
          pkg_manager: pnpm

      - name: remove sample mmd file
        run: |
          git config --global user.name ${{github.actor}}
          git config --global user.email ${{github.actor_id}}@github_workflow.com
          git rm public/sample.mmd
          git commit -m "test: remove .mmd test artifact"
          git push
